<Project>
  <ItemGroup>
    <PackageVersion Include="Corvus.Text.Json.Validator" Version="5.7.5" />
    <PackageVersion Include="Gil" Version="0.15.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>
</Project>
